# **Operasi Baris Elementer Pada Matriks🐳**
---

<img src ="bobob.jpeg" width = "150">  **"Apa Itu Operasi Bilangan Elementer ?"**

## **2.1 Operasi Baris Elementer Pada Matriks**

---


### **2.1.1 Definisi Operasi Baris Pada Matriks**
Operasi Baris Elementer (OBE) adalah operasi dasar yang dilakukan terhadap baris-baris suatu matriks dengan tujuan mengubah bentuk matriks menjadi lebih sederhana tanpa mengubah solusi sistem persamaan linear yang direpresentasikan oleh matriks tersebut.<br>

Dengan kata lain, operasi ini hanya mengubah tampilan matriks, tetapi nilai solusi tetap sama (ekuivalen).<br>

Operasi baris elementer banyak digunakan dalam :<br>

+ penyelesaian Sistem Persamaan Linear (SPL),

+ metode eliminasi Gauss,

+ metode Gauss–Jordan,

+ pencarian invers matriks,

+ menentukan rank matriks.

Proses mengubah suatu matriks menggunakan operasi baris elementer disebut **reduksi baris (row reduction)**. Dua matriks disebut **ekuivalen baris (row quivalen)** jika salah satunya dapat diperoleh dari yang lain melalui sejumlah hingga operasi baris elementer.<br>

1️⃣ **Pertukaran Dua Baris (Row Switching)**<br>
Menukar posisi dua baris dalam matriks.<br>

Notasi:<br>

$$
R_i \leftrightarrow R_j
$$

Makna:
Baris ke-𝑖 ditukar dengan baris ke-j.

Contoh:
$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\rightarrow
\begin{bmatrix}
3 & 4 \\
1 & 2
\end{bmatrix}
$$


2️⃣ **Perkalian Baris dengan Konstanta (Row Scaling)**

Mengalikan semua elemen dalam satu baris dengan suatu bilangan bukan nol.<br>

Notasi:
$$
R_i \rightarrow kR_i,\quad k \neq 0
$$

Makna:<br>
Setiap elemen pada baris ke-𝑖 dikalikan konstanta 
𝑘.<br>

Contoh:
$$
R_1 \rightarrow 2R_1
$$
$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\rightarrow
\begin{bmatrix}
2 & 4 \\
3 & 4
\end{bmatrix}
$$


3️⃣ **Penjumlahan Baris (Row Replacement)**

Menambahkan kelipatan suatu baris ke baris lainnya.<br>

Notasi:
$$
R_i \rightarrow R_i + kR_j
$$

Makna:<br>
Baris ke-𝑖 diganti dengan hasil penjumlahan baris ke-𝑖 dan kelipatan baris ke-𝑗.

Contoh:
$$
R_2 \rightarrow R_2 - 3R_1
$$
$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1 & 2 \\
0 & -2
\end{bmatrix}
$$

---

### **2.1.2 Notasi Operasi Bilangan Elementer**
Notasi operasi baris elementer digunakan untuk menunjukkan perubahan yang dilakukan pada baris suatu matriks tanpa menuliskan seluruh proses perhitungan.<br>
Biasanya huruf 𝑅 digunakan sebagai singkatan dari **Row (baris)**.

1. **Notasi Pertukaran Baris**<br>
Bentuk notasi :
$$
R_i \leftrightarrow R_j
$$

Arti notasi :<br>
+ $R_{i}$ : Baris ke-$i$<br>
+ $R_{j}$ : Baris ke-𝑗<br>
+ ↔       : Ditukar<br>

---

2. **Notasi Perkalian Baris Dengan Konstanta**<br>
Bentuk notasi :
$$
R_i \rightarrow kR_i,\quad k \neq 0
$$

Arti notasi :
+ $k$            : Konstanta (bilangan real)
+ $k$ $ \neq $ 0 : Tidak Boleh nol
+ →              : diganti menjadi

---

3. **Notasi Penjumlahan Baris (Penggantian Baris)**<br>
Bentuk notasi :
$$
R_i \rightarrow R_i + kR_j
$$

Arti notasi :
+ Baris $i$ diganti hasil penjumlahan :<br>
    + Baris $i$ lama
    + Ditambah kelipatan baris $j$

---

### 2.1.3 Langkah - Langkah Menjalankan Operasi Baris Elementer
Eliminasi Gauss (Gaussian elimination) adalah algoritma yang digunakan untuk mengubah suatu matriks menjadi bentuk eselon baris (row echelon form) dengan menggunakan operasi baris elementer.<br>
Metode ini menerima sebuah matriks 𝐴 sebagai input dan menghasilkan matriks 𝐵 yang ekuivalen baris.<br>

**Langkah-Langkah Eliminasi Gauss :**<br>
1. Menentukan Pivot Pertama<br>
Temukan kolom paling kiri yang memiliki elemen tak nol.
Jika perlu, lakukan **pertukaran baris (row swap)** untuk memindahkan baris dengan elemen tak nol tersebut ke posisi paling atas.<br>

2. Membuat Leading 1<br>
Kalikan baris teratas (baris pivot) dengan suatu skalar sehingga elemen utama (pivot) menjadi 1.
Elemen utama ini disebut **eading one**.<br>

3. Membuat Nol di Bawah Pivot<br>
Untuk setiap baris di bawah baris pivot, lakukan operasi:<br>
$R_i \rightarrow R_i + k R_{\text{pivot}}$ <br>
<agar semua elemen di bawah pivot menjadi nol.

4. Ulangi Proses
Ulangi langkah 1–3 pada submatriks yang berada di bawah baris pivot terakhir.<br>
Proses ini dilanjutkan sampai seluruh matriks berada dalam bentuk eselon baris.

### **2.1.4 Contoh Proses Eliminasi Gauss**
Selesaikan sistem persamaan berikut:

$$
\begin{cases}
x + 2y + z = 9 \\
2x + 3y + 4z = 20 \\
3x + y + 3z = 13
\end{cases}
$$

### 1. Bentuk Matriks Augmented

$$
\left(
\begin{array}{ccc|c}
1 & 2 & 1 & 9 \\
2 & 3 & 4 & 20 \\
3 & 1 & 3 & 13
\end{array}
\right)
$$

### 2. Eliminasi Kolom Pertama

$$
R_2 \rightarrow R_2 - 2R_1
$$

$$
R_3 \rightarrow R_3 - 3R_1
$$

Hasil:

$$
\left(
\begin{array}{ccc|c}
1 & 2 & 1 & 9 \\
0 & -1 & 2 & 2 \\
0 & -5 & 0 & -14
\end{array}
\right)
$$

### 3. Eliminasi Kolom Kedua

$$
R_3 \rightarrow R_3 - 5R_2
$$

Hasil:

$$
\left(
\begin{array}{ccc|c}
1 & 2 & 1 & 9 \\
0 & -1 & 2 & 2 \\
0 & 0 & -10 & -24
\end{array}
\right)
$$

### 4. Substitusi Mundur

Dari baris ketiga:

$$
-10z = -24
$$

$$
z = \frac{12}{5}
$$

Baris kedua:

$$
-y + 2z = 2
$$

$$
-y + 2\left(\frac{12}{5}\right) = 2
$$

$$
-y + \frac{24}{5} = 2
$$

$$
-y = -\frac{14}{5}
$$

$$
y = \frac{14}{5}
$$

Baris pertama:

$$
x + 2y + z = 9
$$

$$
x + 2\left(\frac{14}{5}\right) + \frac{12}{5} = 9
$$

$$
x + \frac{40}{5} = 9
$$

$$
x + 8 = 9
$$

$$
x = 1
$$

Hasil Akhir

$$
x = 1, \quad y = \frac{14}{5}, \quad z = \frac{12}{5}
$$

## **Pengerjan Soal OBE Dengan Coding**
1. $$
\begin{cases}
x + 2y + z = 9 \\
2x + 3y + 4z = 20 \\
3x + y + 3z = 13
\end{cases}
$$

In [1]:
# Jawab :
import numpy as np

# Membuat matriks augmented
A = np.array([
    [1, 2, 1, 9],
    [2, 3, 4, 20],
    [3, 1, 3, 13]
], dtype=float)

n = len(A)

# Proses Eliminasi Gauss (Forward Elimination)
for i in range(n):
    
    # Membuat pivot = 1 (jika tidak nol)
    if A[i][i] != 0:
        A[i] = A[i] / A[i][i]
    
    # Menghilangkan elemen di bawah pivot
    for j in range(i+1, n):
        A[j] = A[j] - A[j][i] * A[i]

print("Matriks setelah eliminasi:")
print(A)

# Substitusi Mundur (Back Substitution)
x = np.zeros(n)

for i in range(n-1, -1, -1):
    x[i] = A[i][-1] - np.dot(A[i, i+1:n], x[i+1:n])

print("\nSolusi:")
for i in range(n):
    print(f"x{i+1} =", x[i])

ModuleNotFoundError: No module named 'numpy'

2. Selesaikan sistem persamaan linear berikut dengan metode Eliminasi Gauss:

$$
\begin{cases}
2x - y + 3z = 7 \\
4x + 2y - z = 1 \\
-2x + y + 2z = 4
\end{cases}
$$

In [4]:
#Jawab :
import numpy as np

# Matriks augmented
A = np.array([
    [2, -1, 3, 7],
    [4,  2, -1, 1],
    [-2, 1,  2, 4]
], dtype=float)

n = len(A)

print("Matriks Awal:")
print(A)

# ======================
# Eliminasi Gauss (OBE)
# ======================
for i in range(n):
    
    # Normalisasi pivot menjadi 1
    if A[i][i] != 0:
        A[i] = A[i] / A[i][i]
    
    # Eliminasi elemen di bawah pivot
    for j in range(i+1, n):
        A[j] = A[j] - A[j][i] * A[i]

print("\nMatriks Setelah Eliminasi:")
print(A)

# ======================
# Substitusi Mundur
# ======================
x = np.zeros(n)

for i in range(n-1, -1, -1):
    x[i] = A[i][-1] - np.dot(A[i, i+1:n], x[i+1:n])

print("\nSolusi:")
print("x =", x[0])
print("y =", x[1])
print("z =", x[2])

Matriks Awal:
[[ 2. -1.  3.  7.]
 [ 4.  2. -1.  1.]
 [-2.  1.  2.  4.]]

Matriks Setelah Eliminasi:
[[ 1.   -0.5   1.5   3.5 ]
 [ 0.    1.   -1.75 -3.25]
 [ 0.    0.    1.    2.2 ]]

Solusi:
x = 0.5
y = 0.6000000000000005
z = 2.2


**Soal PPT**<br>

Selesaikan sistem persamaan linear berikut:

$$
\begin{cases}
8x_1 + x_2 + x_3 = 19 \\
x_1 + 2x_2 + 3x_3 = 9 \\
2x_1 + x_2 - x_3 = 5
\end{cases}
$$

In [5]:
import numpy as np

# Matriks augmented
A = np.array([
    [8, 1, 1, 19],
    [1, 2, 3, 9],
    [2, 1, -1, 5]
], dtype=float)

n = len(A)

print("Matriks Awal:")
print(A)

# ======================
# Eliminasi Gauss (OBE)
# ======================
for i in range(n):
    
    # Normalisasi pivot menjadi 1
    if A[i][i] != 0:
        A[i] = A[i] / A[i][i]
    
    # Eliminasi elemen di bawah pivot
    for j in range(i+1, n):
        A[j] = A[j] - A[j][i] * A[i]

print("\nMatriks Setelah Eliminasi:")
print(A)

# ======================
# Substitusi Mundur
# ======================
x = np.zeros(n)

for i in range(n-1, -1, -1):
    x[i] = A[i][-1] - np.dot(A[i, i+1:n], x[i+1:n])

print("\nSolusi:")
print("x1 =", x[0])
print("x2 =", x[1])
print("x3 =", x[2])

Matriks Awal:
[[ 8.  1.  1. 19.]
 [ 1.  2.  3.  9.]
 [ 2.  1. -1.  5.]]

Matriks Setelah Eliminasi:
[[ 1.          0.125       0.125       2.375     ]
 [ 0.          1.          1.53333333  3.53333333]
 [-0.         -0.          1.          1.        ]]

Solusi:
x1 = 2.0
x2 = 2.0
x3 = 0.9999999999999998
